const imageData = [
	{
		"id": 1,
		"type": "tattoo",
		"image": "tattoo-1-abstraction.jpg",
		"style": "abstraction",
		"name": "абстракція",
	},
	{
		"id": 2,
		"type": "tattoo",
		"image": "tattoo-2-abstraction.jpg",
		"style": "abstraction",
		"name": "трикутник",
	},
	{
		"id": 9,
		"type": "sketch",
		"image": "sketch-3-abstraction-scorpio.jpg",
		"style": "abstraction",
		"name": "скорпіон",
	},
	{
		"id": 3,
		"type": "tattoo",
		"image": "tattoo-3-abstraction.jpg",
		"style": "abstraction",
		"name": "журавлик",
	},
	{
		"id": 4,
		"type": "tattoo",
		"image": "tattoo-4-abstraction.jpg",
		"style": "abstraction",
		"name": "птах",
	},
	{
		"id": 5,
		"type": "tattoo",
		"image": "tattoo-5-abstraction.jpg",
		"style": "abstraction",
		"name": "лисиця",
	},
	{
		"id": 8,
		"type": "sketch",
		"image": "sketch-2-abstraction-triangle.jpg",
		"style": "abstraction",
		"name": "лотос",
	},
	{
		"id": 6,
		"type": "tattoo",
		"image": "tattoo-6-abstraction.jpg",
		"style": "abstraction",
		"name": "абстракція",
	},
	{
		"id": 7,
		"type": "sketch",
		"image": "sketch-1-abstraction-planet.jpg",
		"style": "abstraction",
		"name": "космос",
	},
	{
		"id": 10,
		"type": "tattoo",
		"image": "tattoo-1-aquarel.jpg",
		"style": "aquarel",
		"name": "кулька",
	},
	{
		"id": 11,
		"type": "tattoo",
		"image": "tattoo-2-aquarel.jpg",
		"style": "aquarel",
		"name": "діамант",
	},
	{
		"id": 12,
		"type": "sketch",
		"image": "sketch-1-aquarel.jpg",
		"style": "aquarel",
		"name": "лисиця",
	},
	{
		"id": 13,
		"type": "tattoo",
		"image": "tattoo-3-aquarel.jpg",
		"style": "aquarel",
		"name": "метелик",
	},
	{
		"id": 14,
		"type": "tattoo",
		"image": "tattoo-4-aquarel.jpg",
		"style": "aquarel",
		"name": "кішка",
	},
	{
		"id": 15,
		"type": "sketch",
		"image": "sketch-2-aquarel.jpg",
		"style": "aquarel",
		"name": "собака",
	},
	{
		"id": 16,
		"type": "tattoo",
		"image": "tattoo-5-aquarel.jpg",
		"style": "aquarel",
		"name": "вовк",
	},
	{
		"id": 17,
		"type": "tattoo",
		"image": "tattoo-6-aquarel.jpg",
		"style": "aquarel",
		"name": "перо",
	},
	{
		"id": 18,
		"type": "sketch",
		"image": "sketch-3-aquarel.jpg",
		"style": "aquarel",
		"name": "кохання",
	},
	{
		"id": 19,
		"type": "tattoo",
		"image": "tattoo-1-akula.jpg",
		"style": "abstraction",
		"name": "акула",
	},
	{
		"id": 20,
		"type": "tattoo",
		"image": "tattoo-2-akula.jpg",
		"style": "old school",
		"name": "акула",
	},
	{
		"id": 21,
		"type": "tattoo",
		"image": "tattoo-3-akula.jpg",
		"style": "aquarel",
		"name": "акула",
	},
	{
		"id": 22,
		"type": "sketch",
		"image": "sketch-1-akula.jpg",
		"style": "abstraction",
		"name": "акула",
	},
	{
		"id": 23,
		"type": "tattoo",
		"image": "tattoo-4-akula.jpg",
		"style": "old school",
		"name": "акула",
	},
	{
		"id": 24,
		"type": "sketch",
		"image": "sketch-2-akula.jpg",
		"style": "trible",
		"name": "акула",
	},
	{
		"id": 25,
		"type": "tattoo",
		"image": "tattoo-5-akula.jpg",
		"style": "old school",
		"name": "акула",
	},
	{
		"id": 26,
		"type": "tattoo",
		"image": "tattoo-6-akula.jpg",
		"style": "abstraction",
		"name": "акула",
	},
	{
		"id": 27,
		"type": "sketch",
		"image": "sketch-3-akula.jpg",
		"style": "abstraction",
		"name": "акула",
	},
	{
		"id": 28,
		"type": "tattoo",
		"image": "tattoo-1-almaz.jpg",
		"style": "old school",
		"name": "діамант",
	},
	{
		"id": 29,
		"type": "tattoo",
		"image": "tattoo-2-almaz.jpg",
		"style": "old school",
		"name": "діамант",
	},
	{
		"id": 30,
		"type": "sketch",
		"image": "sketch-1-almaz.jpg",
		"style": "old school",
		"name": "діамант",
	},
	{
		"id": 31,
		"type": "tattoo",
		"image": "tattoo-3-almaz.jpg",
		"style": "abstraction",
		"name": "діамант",
	},
	{
		"id": 32,
		"type": "tattoo",
		"image": "tattoo-4-almaz.jpg",
		"style": "abstraction",
		"name": "діамант",
	},
	{
		"id": 33,
		"type": "sketch",
		"image": "sketch-2-almaz.jpg",
		"style": "abstraction",
		"name": "діамант",
	},
	{
		"id": 34,
		"type": "tattoo",
		"image": "tattoo-5-almaz.jpg",
		"style": "traditional",
		"name": "діамант",
	},
	{
		"id": 35,
		"type": "tattoo",
		"image": "tattoo-6-almaz.jpg",
		"style": "traditional",
		"name": "діамант",
	},
	{
		"id": 36,
		"type": "sketch",
		"image": "sketch-3-almaz.webp",
		"style": "traditional",
		"name": "діамант",
	},
	{
		"id": 37,
		"type": "tattoo",
		"image": "tattoo-1-amulet.jpg",
		"style": "abstraction",
		"name": "амулет",
	},
	{
		"id": 38,
		"type": "tattoo",
		"image": "tattoo-2-amulet.jpg",
		"style": "traditional",
		"name": "око гора",
	},
	{
		"id": 39,
		"type": "tattoo",
		"image": "tattoo-3-amulet.jpg",
		"style": "traditional",
		"name": "амулет",
	},
	{
		"id": 40,
		"type": "sketch",
		"image": "sketch-1-amulet.jpg",
		"style": "traditional",
		"name": "амулет",
	},
	{
		"id": 41,
		"type": "sketch",
		"image": "sketch-2-amulet.jpg",
		"style": "abstraction",
		"name": "амулет",
	},
	{
		"id": 42,
		"type": "sketch",
		"image": "sketch-3-amulet.jpg",
		"style": "traditional",
		"name": "ангх",
	},
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
	// {
	// 	"id": "",
	// 	"type": "",
	// 	"image": "",
	// 	"style": "",
	// 	"name": "",
	// },
]

export default imageData;